import {CookieContainer} from '../Cookie/CookiePolicyStyled';


export const PrivacyPolicy = () => {
    return (
        <CookieContainer>
            <section className="container">
            <h1>Privacy Policy</h1>
            <p>Effective date: February 15, 2021</p>
            <p>Watchy AB ("us", "we", or "our") operates the Watchy website and the Watchy mobile application (the "Service").</p>
            <p>This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>
            <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</p>
            <h1>Definisions</h1>
            <h1>Personal data</h1>
            <p>Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
            <h1>Usage data</h1>
            <p>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
            <h1>Cookies</h1>
            <p>Cookies are small pieces of data stored on a User’s device.</p>
            <h1>Data controller</h1>
            <p>Data Controller means a person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>
            <h1>Data processor (Or service providers)</h1>
            <p>Data Processor (or Service Provider) means any person (other than an employee of the Data Controller) who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively</p>
            <h1>Data subject</h1>
            <p>Data Subject is any living individual who is the subject of Personal Data.</p>
            <h1>User</h1>
            <p>The User is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>
            <h1>Informaion Collection and use</h1>
            <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
            <h1>Types if data collected</h1>
            <h4>Personal Data</h4>
            <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to your email address, first name, and last name.</p>
            <h4>Usage Data</h4>
            <p>We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device ("Usage Data")</p>
            <p>This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            <p>When you access the Service by or through a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.</p>
            <h4>Tracking Data</h4>
            <p>We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</p>
            <p>Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</p>
            <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
            <ul>
                <li>Session Cookies. We use Session Cookies to operate our Service.</li>
                <li>Preference Cookies. We use Preference Cookies to remember your preferences and various settings.</li>
                <li>Security Cookies. We use Security Cookies for security purposes.</li>
                <li>To enable advertisements delivery, including behavioral advertising</li>
            </ul>
            <h1>Use of data</h1>
            <p>Watchy AB uses the collected data for various purposes:</p>
            <ul>
                <li>Session Cookies. We use Session Cookies to operate our Service.</li>
                <li>Preference Cookies. We use Preference Cookies to remember your preferences and various settings.</li>
                <li>Security Cookies. We use Security Cookies for security purposes.</li>
                <li>To enable advertisements delivery, including behavioral advertising</li>
                <li>To provide and maintain our Service</li>
                <li>To notify you about changes to our Service</li>
                <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                <li>To provide customer support</li>
                <li>To gather analysis or valuable information so that we can improve our Service</li>
                <li>To monitor the usage of our Service</li>
                <li>To detect, prevent and address technical issues</li>
                <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
            </ul>
            <h1>Retenation of data</h1>
            <p>Watchy AB will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
            <p>Watchy AB will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>
            <h1>Tranfer of data</h1>
            <p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>
            <p>If you are located outside Sweden and choose to provide information to us, please note that we transfer the data, including Personal Data, to Sweden and process it there.</p>
            <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
            <p>Watchy AB will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place, including the security of your data and other personal information.</p>
            <h1>Disclosure of data</h1>
            <h4>Buisness transaction</h4>
            <p>If Watchy AB is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Polic</p>
            <h4>Legal requirements for law inforcment</h4>
            <p>Under certain circumstances, Watchy AB may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
            <h4>Legal requirements</h4>
            <p>Watchy AB may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
            <ul>
                <li>To comply with a legal obligation</li>
                <li>To protect and defend the rights or property of Watchy AB</li>
                <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
                <li>To protect the personal safety of users of the Service or the public</li>
                <li>To protect against legal liability</li>
            </ul>
            <h1>Security of data</h1>
            <p>The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
            <h1>"Do not track" signals</h1>
            <p>We do not support Do Not Track ("DNT"). Do Not Track is a preference you can set in the preferences of settings of your web browser to inform websites that you do not want to be tracked.</p>
            <h1>Your rights</h1>
            <p>Watchy AB aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data</p>
            <p>Whenever made possible, you can update your Personal Data directly within your account settings section. If you are unable to change your Personal Data, please contact us to make the required changes.</p>
            <p>If you wish to be informed what Personal Data we hold about you or if you want it to be removed from our systems, please contact us.</p>
            <p>In certain circumstances, you have the right:</p>
            <ul>
                <li>To access and receive a copy of the Personal Data we hold about you</li>
                <li>To rectify any Personal Data held about you that is inaccurate</li>
                <li>To request the deletion of Personal Data held about you</li>
                <li>You have the right to data portability for the information you provide to Watchy AB. You can request to obtain a copy of your Personal Data in a commonly used electronic format so that you can manage and move it.</li>
            </ul>
            <p>Please note that we may ask you to verify your identity before responding to such requests.</p>
            <h1>Contact</h1>
            <p>If you have any questions about this Privacy Policy, please contact us: <a href="privacy@watchy.com">privacy@watchy.com</a> </p>


            </section>
        </CookieContainer>    
    )
}
